server:
  port: 7000
  address: 0.0.0.0
lavalink:
  server:
    password: "celestial"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 100
    youtubeSearchEnabled: true
    gc-warnings: false

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
sentry:
  dsn: ""

logging:
  file:
    max-history: 0
    max-size: 0MB
  path: ""

  level:
    root: INFO
    lavalink: INFO